### ISSUE TITLE
cannot create weak reference to 'builtin_function_or_method' object

### ISSUE THREAD

**Issue by XiongDuan** [fabiotosi92/monoResMatch-Tensorflow#4]
Traceback (most recent call last):
  File "main.py", line 281, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "main.py", line 272, in main
    monoResMatch, dataloader = configure_network(network_params, dataloader_params)
  File "main.py", line 99, in configure_network
    dataloader_params)
  File "/home/dx/code/monoResMatch-Tensorflow/dataloader.py", line 80, in __init__
    left_image_o = self.read_image(self.left_image_path)
  File "/home/dx/code/monoResMatch-Tensorflow/dataloader.py", line 113, in read_image
    path_length = string_length_tf(image_path)[0]
  File "/home/dx/code/monoResMatch-Tensorflow/dataloader.py", line 13, in string_length_tf
    return tf.py_func(len, [t], [tf.int64])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/script_ops.py", line 480, in py_func
    return py_func_common(func, inp, Tout, stateful, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/script_ops.py", line 462, in py_func_common
    func=func, inp=inp, Tout=Tout, stateful=stateful, eager=False, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/script_ops.py", line 257, in _internal_py_func
    token = _py_funcs.insert(func)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/script_ops.py", line 144, in insert
    self._funcs[token] = func
  File "/usr/lib/python2.7/weakref.py", line 108, in __setitem__
    self.data[key] = KeyedRef(value, self._remove, key)
  File "/usr/lib/python2.7/weakref.py", line 278, in __new__
    self = ref.__new__(type, ob, callback)
TypeError: Traceback (most recent call last):
  File "main.py", line 281, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "main.py", line 272, in main
    monoResMatch, dataloader = configure_network(network_params, dataloader_params)
  File "main.py", line 99, in configure_network
    dataloader_params)
  File "/home/dx/code/monoResMatch-Tensorflow/dataloader.py", line 80, in __init__
    left_image_o = self.read_image(self.left_image_path)
  File "/home/dx/code/monoResMatch-Tensorflow/dataloader.py", line 113, in read_image
    path_length = string_length_tf(image_path)[0]
  File "/home/dx/code/monoResMatch-Tensorflow/dataloader.py", line 13, in string_length_tf
    return tf.py_func(len, [t], [tf.int64])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/script_ops.py", line 480, in py_func
    return py_func_common(func, inp, Tout, stateful, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/script_ops.py", line 462, in py_func_common
    func=func, inp=inp, Tout=Tout, stateful=stateful, eager=False, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/script_ops.py", line 257, in _internal_py_func
    token = _py_funcs.insert(func)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/script_ops.py", line 144, in insert
    self._funcs[token] = func
  File "/usr/lib/python2.7/weakref.py", line 108, in __setitem__
    self.data[key] = KeyedRef(value, self._remove, key)
  File "/usr/lib/python2.7/weakref.py", line 278, in __new__
    self = ref.__new__(type, ob, callback)
TypeError: cannot create weak reference to 'builtin_function_or_method' object

Hi，there occurs a problem that "TypeError: cannot create weak reference to 'builtin_function_or_method' object", My tensorflow-gpu version is 1.14.0， must I change it to 1.8？

**Comment by fabiotosi92** [comment]
Hi! Yes, it is Tensorflow-gpu version issue. You should have no problem changing to 1.8.
